package com.The_L.client;

import com.The_L.Message.MessagePassing;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
/**
 *
 * @author rajat_000
 */
public class ChatUI extends javax.swing.JFrame {
    public static ConnectToServer cts;
    public DefaultListModel model;
    public File file;
    
    public ChatUI(ConnectToServer cts) {
        initComponents();
        this.setTitle("THE L CHAT");
        //this.model = cts.model;
        this.cts = cts;
        model.addElement("ALL");
        jTOnline.setSelectedIndex(0);
        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent e) {
                jBSignOutActionPerformed(null);
            }
            
        });
        
    }
    public boolean isWin32(){
        return System.getProperty("os.name").startsWith("Windows");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jTBrowseFile = new javax.swing.JLabel();
        jTBrowseFile1 = new javax.swing.JLabel();
        jBSendMessage = new javax.swing.JButton();
        jTMessage = new javax.swing.JTextField();
        jBVoiceRecorder = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTInbox = new javax.swing.JTextArea();
        jLLine = new javax.swing.JLabel();
        jLLine1 = new javax.swing.JLabel();
        jBSignOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTOnline = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 51, 255));
        Title.setText("The_L_CHAT");

        jTBrowseFile.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jTBrowseFile.setForeground(new java.awt.Color(0, 153, 153));
        jTBrowseFile.setText("Inbox ");

        jTBrowseFile1.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jTBrowseFile1.setForeground(new java.awt.Color(0, 153, 153));
        jTBrowseFile1.setText("ONLINE");

        jBSendMessage.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jBSendMessage.setForeground(new java.awt.Color(0, 153, 0));
        jBSendMessage.setText("SeND MeSSAGE");
        jBSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSendMessageActionPerformed(evt);
            }
        });

        jBVoiceRecorder.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jBVoiceRecorder.setForeground(new java.awt.Color(0, 102, 102));
        jBVoiceRecorder.setText("Voice Message");
        jBVoiceRecorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoiceRecorderActionPerformed(evt);
            }
        });

        jTInbox.setColumns(20);
        jTInbox.setRows(5);
        jScrollPane3.setViewportView(jTInbox);

        jLLine.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLLine.setForeground(new java.awt.Color(255, 0, 0));
        jLLine.setText("-------------------------------------------------------------------------------------------------------");

        jLLine1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLLine1.setForeground(new java.awt.Color(255, 0, 0));
        jLLine1.setText("-------------------------------------------------------------------------------------------------------");

        jBSignOut.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jBSignOut.setForeground(new java.awt.Color(153, 0, 0));
        jBSignOut.setText("SIGN OUT");
        jBSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSignOutActionPerformed(evt);
            }
        });

        jTOnline.setModel((model = new DefaultListModel()));
        jScrollPane1.setViewportView(jTOnline);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBVoiceRecorder)
                        .addGap(18, 18, 18)
                        .addComponent(jTMessage))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jTBrowseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTBrowseFile1)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLLine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTBrowseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTBrowseFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBVoiceRecorder))
                .addGap(18, 18, 18)
                .addComponent(jBSendMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLLine1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSendMessageActionPerformed
        String msg = jTMessage.getText().trim();
        String target = jTOnline.getSelectedValue().toString();
        if(!msg.isEmpty() && !target.isEmpty()){
            jTMessage.setText("");
            cts.client.sendMessage(new MessagePassing("message", cts.username, target,msg));
        }
    }//GEN-LAST:event_jBSendMessageActionPerformed

    private void jBVoiceRecorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoiceRecorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBVoiceRecorderActionPerformed

    private void jBSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSignOutActionPerformed
        // TODO add your handling code here:
          cts.client.sendMessage(new MessagePassing("message", cts.username, "ALL",".bye"));     
    }//GEN-LAST:event_jBSignOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new ChatUI(cts).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    public javax.swing.JButton jBSendMessage;
    public javax.swing.JButton jBSignOut;
    public javax.swing.JButton jBVoiceRecorder;
    private javax.swing.JLabel jLLine;
    private javax.swing.JLabel jLLine1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jTBrowseFile;
    private javax.swing.JLabel jTBrowseFile1;
    public javax.swing.JTextArea jTInbox;
    private javax.swing.JTextField jTMessage;
    public javax.swing.JList jTOnline;
    // End of variables declaration//GEN-END:variables
}
