/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.The_L.client;

import com.The_L.Message.MessagePassing;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rajat_000
 */
public class ConnectToServer extends javax.swing.JFrame {
    public int port;
    public String serverAddr, username, password;
    public DefaultListModel model;
    public Thread clientThread;
    public Client client;
    public ChatUI ui;
   
    /**
     * Creates new form ConnectToServer
     */
    public ConnectToServer() {
        initComponents();
        this.setTitle("Login");
        ui = new ChatUI(this);
        model = ui.model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jLLine = new javax.swing.JLabel();
        jTBrowseFile2 = new javax.swing.JLabel();
        jTHost = new javax.swing.JTextField();
        jBConnect = new javax.swing.JButton();
        jTBrowseFile3 = new javax.swing.JLabel();
        jTPort = new javax.swing.JTextField();
        jLLine1 = new javax.swing.JLabel();
        jTUserName = new javax.swing.JTextField();
        jTBrowseFile4 = new javax.swing.JLabel();
        jTBrowseFile5 = new javax.swing.JLabel();
        jBLogin = new javax.swing.JButton();
        jBSignup = new javax.swing.JButton();
        jTPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 51, 255));
        Title.setText("The_L_LOGIN");

        jLLine.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLLine.setForeground(new java.awt.Color(255, 0, 0));
        jLLine.setText("--------------------------------------------------------------------");

        jTBrowseFile2.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jTBrowseFile2.setForeground(new java.awt.Color(0, 153, 153));
        jTBrowseFile2.setText("HOST ADDRESS");

        jTHost.setText("localhost");
        jTHost.setEnabled(true);
        jTHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTHostActionPerformed(evt);
            }
        });

        jBConnect.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jBConnect.setForeground(new java.awt.Color(51, 204, 0));
        jBConnect.setText("Connect");
        jBConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConnectActionPerformed(evt);
            }
        });

        jTBrowseFile3.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jTBrowseFile3.setForeground(new java.awt.Color(0, 153, 153));
        jTBrowseFile3.setText("PORT");

        jTPort.setText("59120");
        jTPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPortActionPerformed(evt);
            }
        });

        jLLine1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLLine1.setForeground(new java.awt.Color(255, 0, 0));
        jLLine1.setText("--------------------------------------------------------------------");

        jTUserName.setText(" ");
        jTUserName.setEditable(false);

        jTBrowseFile4.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jTBrowseFile4.setForeground(new java.awt.Color(0, 153, 153));
        jTBrowseFile4.setText("User Name");

        jTBrowseFile5.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jTBrowseFile5.setForeground(new java.awt.Color(0, 153, 153));
        jTBrowseFile5.setText("PASSWORD");

        jBLogin.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jBLogin.setForeground(new java.awt.Color(51, 204, 0));
        jBLogin.setText("LOGIN");
        jBLogin.setEnabled(false);
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });

        jBSignup.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jBSignup.setForeground(new java.awt.Color(51, 204, 0));
        jBSignup.setText("SIGNUP");
        jBSignup.setEnabled(false);
        jBSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTBrowseFile4)
                                .addGap(44, 44, 44)
                                .addComponent(jTUserName))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTBrowseFile5)
                                    .addGap(47, 47, 47)
                                    .addComponent(jTPassword))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTBrowseFile2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTHost)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTBrowseFile3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTPort, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLLine1)
                                        .addComponent(jLLine)
                                        .addComponent(jBConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(1, 1, 1)
                .addComponent(jLLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTBrowseFile2)
                    .addComponent(jTHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTBrowseFile3)
                    .addComponent(jTPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBConnect)
                .addGap(16, 16, 16)
                .addComponent(jLLine1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTBrowseFile4)
                    .addComponent(jTUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTBrowseFile5)
                    .addComponent(jTPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLogin)
                    .addComponent(jBSignup))
                .addGap(29, 29, 29))
        );

        jTPassword.setEditable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConnectActionPerformed
        serverAddr = jTHost.getText();
        port = Integer.parseInt(jTPort.getText());
        System.out.println(port+" "+serverAddr);
        if(!serverAddr.isEmpty() && !jTPort.getText().isEmpty()){
            try{
                client = new Client(this);
                clientThread = new Thread(client);
                clientThread.start();
                client.sendMessage(new MessagePassing("test", "testUser", "testContent", "SERVER"));
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null," Server not found\n");
            }
        }
        else{
                JOptionPane.showMessageDialog(null," Server not found\n");   
        }
    }//GEN-LAST:event_jBConnectActionPerformed

    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        username = jTUserName.getText().trim();
        password = jTPassword.getText().trim();
        
        if(!username.isEmpty() && !password.isEmpty()){
            client.sendMessage( new MessagePassing("login", username, "SERVER", password));
        }
    }//GEN-LAST:event_jBLoginActionPerformed

    private void jBSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSignupActionPerformed
        // TODO add your handling code here:
        username = jTUserName.getText().trim() ;
        password = jTPassword.getText().trim();
        
        if(!username.isEmpty() && !password.isEmpty()){
            client.sendMessage(new MessagePassing("signup", username, "SERVER", password));
        }
    }//GEN-LAST:event_jBSignupActionPerformed

    private void jTHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTHostActionPerformed

    private void jTPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnectToServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnectToServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnectToServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnectToServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnectToServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    public javax.swing.JButton jBConnect;
    public javax.swing.JButton jBLogin;
    public javax.swing.JButton jBSignup;
    private javax.swing.JLabel jLLine;
    private javax.swing.JLabel jLLine1;
    private javax.swing.JLabel jTBrowseFile2;
    private javax.swing.JLabel jTBrowseFile3;
    private javax.swing.JLabel jTBrowseFile4;
    private javax.swing.JLabel jTBrowseFile5;
    public javax.swing.JTextField jTHost;
    public javax.swing.JPasswordField jTPassword;
    public javax.swing.JTextField jTPort;
    public javax.swing.JTextField jTUserName;
    // End of variables declaration//GEN-END:variables
}
