package com.The_L.server;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author rajat_000
 */
public class ServerUI extends javax.swing.JFrame {
    
    public Server server;
    public Thread serverThread;
    public String filePath = "";
    /**
     * Creates new form ServerUI
     */
    public ServerUI() {
        initComponents();
        this.setTitle("THE L SERVER");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jTBrowseFile = new javax.swing.JLabel();
        jTDBFile = new javax.swing.JTextField();
        jBBrowse = new javax.swing.JButton();
        jBStartServer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAServer = new javax.swing.JTextArea();
        jLLine = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 51, 255));
        Title.setText("The_L_SERVER");

        jTBrowseFile.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jTBrowseFile.setForeground(new java.awt.Color(0, 153, 153));
        jTBrowseFile.setText("Database File :");

        jTDBFile.setText(" ");
        jTDBFile.setEditable(false);

        jBBrowse.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jBBrowse.setText("Browse");
        jBBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBrowseActionPerformed(evt);
            }
        });

        jBStartServer.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jBStartServer.setForeground(new java.awt.Color(0, 153, 0));
        jBStartServer.setText("Start Server");
        jBStartServer.setEnabled(false);
        jBStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBStartServerActionPerformed(evt);
            }
        });

        jTAServer.setColumns(20);
        jTAServer.setRows(5);
        jScrollPane1.setViewportView(jTAServer);
        jTAServer.setEditable(false);

        jLLine.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLLine.setForeground(new java.awt.Color(255, 0, 0));
        jLLine.setText("---------------------------------------------------------------------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTBrowseFile)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTDBFile, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jBBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(Title)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLLine)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTBrowseFile)
                            .addComponent(jTDBFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jBBrowse)))
                .addGap(18, 18, 18)
                .addComponent(jBStartServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBrowseActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new java.io.File("."));
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setDialogTitle("Browse");
        if ( fileChooser.showOpenDialog(jBBrowse) == JFileChooser.APPROVE_OPTION)
        {
        }
        filePath = fileChooser.getSelectedFile().getAbsolutePath();
        if(this.isWin32())
        { 
            filePath = filePath.replace("\\", "/"); 
        }
        jTDBFile.setText(filePath);
        jBStartServer.setEnabled(true);
    }//GEN-LAST:event_jBBrowseActionPerformed
    public void retryStart(int port){
        if(server != null){ server.stop(); }
        server = new Server(this, port);
    }
    private void jBStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBStartServerActionPerformed
       server = new Server(this);
       jBBrowse.setEnabled(false);
       jBStartServer.setEnabled(false);
    }//GEN-LAST:event_jBStartServerActionPerformed
    private boolean isWin32(){
        
        return System.getProperty("os.name").startsWith("Windows");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton jBBrowse;
    private javax.swing.JButton jBStartServer;
    private javax.swing.JLabel jLLine;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTAServer;
    private javax.swing.JLabel jTBrowseFile;
    private javax.swing.JTextField jTDBFile;
    // End of variables declaration//GEN-END:variables
}
